# coding=utf-8

ORDER_LINE_STATUS_ORDERED = 1
ORDER_LINE_STATUS_RETURNED = 2
ORDER_LINE_STATUS_ADDED = 3

ORDER_LINE_STATUS_CHOICES = (

    (ORDER_LINE_STATUS_ORDERED, "Ordered"),
    (ORDER_LINE_STATUS_RETURNED, "Returned"),
    (ORDER_LINE_STATUS_ADDED, "Added"),
)
